 server:
   port: 8080
   servlet:
     context-path: /project

 spring:
   datasource:
     url: "jdbc:mysql://localhost:3306/students"
     username: root
     password: 15022001
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     properties:
       hibernate:
         format_sql: true

